# Generated by Django 4.0.4 on 2022-05-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0002_alter_photo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='url',
            new_name='file',
        ),
    ]
