# Generated by Django 4.0.4 on 2022-05-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0004_remove_photo_file_profile_pronouns'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.FileField(default=None, max_length=128, upload_to=''),
            preserve_default=False,
        ),
    ]
